# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 542)
        MainWindow.setStyleSheet("QMenuBar{\n"
"    background-color: rgb(36, 41, 46);\n"
"    color: rgb(167, 169, 171);\n"
"    \n"
"    font-size: 15px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"\n"
"    padding-left: 20px;\n"
"    padding-top: 10px;\n"
"\n"
"    border: none;\n"
"    \n"
"}\n"
"QMenu{\n"
"    border: none;\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid white;\n"
"    text-decoration: none;\n"
"    list-style: none;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    font-size: 10px;\n"
"    \n"
"    Width: 200px;\n"
"    Height: 100px;\n"
"}\n"
"QMenu,actionSalvar{\n"
"    border-bottom: 1px solid black;\n"
"    font-size: 16px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"}\n"
"QAction,{\n"
"    border: 1px solid black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 698, 42))
        self.menubar.setMinimumSize(QtCore.QSize(0, 36))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuRepository = QtWidgets.QMenu(self.menubar)
        self.menuRepository.setObjectName("menuRepository")
        self.menuBrancg = QtWidgets.QMenu(self.menubar)
        self.menuBrancg.setObjectName("menuBrancg")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.menuFile.addAction(self.actionSalvar)
        self.menuFile.addAction(self.actionAbrir)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuRepository.menuAction())
        self.menubar.addAction(self.menuBrancg.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuRepository.setTitle(_translate("MainWindow", "Repository"))
        self.menuBrancg.setTitle(_translate("MainWindow", "Branch"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
